[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  node_bundler = "esbuild"

# API redirects
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

# SPA redirect - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
