[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  node_bundler = "esbuild"

# API redirects - each endpoint maps to its own function
[[redirects]]
  from = "/api/active-prompt"
  to = "/.netlify/functions/active-prompt"
  status = 200

[[redirects]]
  from = "/api/realtime/client-secret"
  to = "/.netlify/functions/client-secret"
  status = 200

[[redirects]]
  from = "/api/admin/recordings"
  to = "/.netlify/functions/admin-recordings"
  status = 200

[[redirects]]
  from = "/api/admin/prompt"
  to = "/.netlify/functions/admin-prompt"
  status = 200

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200

# Catch-all for other API routes (if needed)
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA redirect - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
